version: 2
updates:
  # Root npm
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    groups:
      all-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
  # Backend npm
  - package-ecosystem: npm
    directory: "/backend"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    groups:
      all-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
  # Lambda npm functions
  - package-ecosystem: npm
    directory: "/infrastructure/aws-sam/functions/anomaly-detection"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    groups:
      all-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: npm
    directory: "/infrastructure/aws-sam/functions/billing-tracking"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    groups:
      all-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: npm
    directory: "/infrastructure/aws-sam/functions/install-tracking"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    groups:
      all-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: npm
    directory: "/infrastructure/aws-sam/functions/merge-tracking"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    groups:
      all-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: npm
    directory: "/infrastructure/aws-sam/functions/onboarding-tracking"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    groups:
      all-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: npm
    directory: "/infrastructure/aws-sam/functions/report-generation"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    groups:
      all-minor-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  # Dockerfiles
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
  - package-ecosystem: docker
    directory: "/backend"
    schedule:
      interval: daily
    open-pull-requests-limit: 1

  # Terraform
  - package-ecosystem: terraform
    directory: "/infrastructure/terraform"
    schedule:
      interval: daily
    open-pull-requests-limit: 1

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 1

  # Additional npm configuration
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
    open-pull-requests-limit: 10
    reviewers:
      - "MichaelWBrennan"
    assignees:
      - "MichaelWBrennan"
    commit-message:
      prefix: "🔄"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    allow:
      - dependency-type: "all"
    # Major updates will be auto-merged if tests pass
    # Remove ignore block to enable major version auto-merge

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    commit-message:
      prefix: "🔄"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
