version: '3.8'

services:
  konivrer-automation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: konivrer-automation-24-7-365
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - AUTOMATION_MODE=continuous
      - AUTOMATION_INTERVAL=60000  # 60 seconds instead of 1 second
      - AUTOMATION_CONTINUOUS=true
      - AUTOMATION_SELF_HEALING=true
      - AUTOMATION_RESOURCE_EFFICIENT=true
    # Set resource limits to prevent container from using too much CPU/memory
    deploy:
      resources:
        limits:
          cpus: '0.50'  # Limit to 50% of a CPU core
          memory: 512M  # Limit memory to 512MB
      restart_policy:
        condition: any
        delay: 30s      # Longer delay between restarts
        max_attempts: 0
        window: 120s
    command: >
      sh -c "chmod +x /app/auto-service.sh && 
             /app/auto-service.sh"
    healthcheck:
      test: ["CMD", "pgrep", "-f", "automation/all-in-one.ts"]
      interval: 60s     # Check health less frequently
      timeout: 10s
      retries: 3
      start_period: 60s # Give more time to start up

  konivrer-automation-monitor:
    image: alpine:latest
    container_name: konivrer-automation-monitor
    restart: always
    depends_on:
      - konivrer-automation
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Set resource limits for the monitor container
    deploy:
      resources:
        limits:
          cpus: '0.10'  # Limit to 10% of a CPU core
          memory: 64M   # Limit memory to 64MB
    command: >
      sh -c "apk add --no-cache docker-cli && 
             while true; do 
               if ! docker ps | grep -q konivrer-automation-24-7-365; then 
                 echo 'Automation container down, restarting...'; 
                 docker restart konivrer-automation-24-7-365 || docker-compose -f /app/docker-compose.continuous.yml up -d konivrer-automation; 
               fi; 
               sleep 60; # Check every minute instead of every 5 seconds
             done"