name: 🐛 Automerge-Pro Bug Report
description: Report a bug in the Automerge-Pro GitHub App
title: "[Bug] "
labels: ["bug", "automerge-pro", "triage"]
assignees:
  - MichaelWBrennan
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report for Automerge-Pro!
        
        Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: input
    id: installation-id
    attributes:
      label: GitHub Installation ID
      description: Your GitHub installation ID (found in repository settings or webhook logs)
      placeholder: "12345"
    validations:
      required: true

  - type: dropdown
    id: tier
    attributes:
      label: License Tier
      description: What license tier are you using?
      options:
        - Free
        - Pro
        - Enterprise
        - Development/Testing
    validations:
      required: true

  - type: input
    id: repository
    attributes:
      label: Repository
      description: Which repository is experiencing the issue?
      placeholder: "owner/repository"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and what you expected to happen instead.
      placeholder: "A clear description of the bug..."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: List the exact steps to reproduce this behavior.
      placeholder: |
        1. Go to...
        2. Create a pull request with...
        3. Wait for...
        4. See error...
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Please share your `.automerge-pro.yml` configuration (remove any sensitive data).
      render: yaml
      placeholder: |
        version: '2.0'
        rules:
          - name: 'my-rule'
            # ... rest of configuration
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output or error messages.
      render: shell
      placeholder: "Paste error messages or webhook payload logs here..."
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this issue?
      options:
        - Low - Minor issue, workaround available
        - Medium - Affects functionality but not critical
        - High - Blocks important functionality
        - Critical - System is unusable or data loss
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        
        **Need immediate support?** For urgent issues on Pro/Enterprise plans:
        - Email: support@automerge-pro.com
        - Discord: https://discord.gg/automerge-pro