name: ❓ Automerge-Pro Support Question
description: Get help with configuration, setup, or usage questions
title: "[Support] "
labels: ["question", "automerge-pro", "support"]
assignees:
  - MichaelWBrennan
body:
  - type: markdown
    attributes:
      value: |
        Need help with Automerge-Pro? We're here to assist!
        
        **Before submitting:** Please check our [documentation](https://docs.automerge-pro.com) and [FAQ](https://docs.automerge-pro.com/faq) first.

  - type: input
    id: installation-id
    attributes:
      label: GitHub Installation ID
      description: Your GitHub installation ID (if applicable)
      placeholder: "12345"
    validations:
      required: false

  - type: dropdown
    id: tier
    attributes:
      label: License Tier
      description: What license tier are you using?
      options:
        - Free
        - Pro
        - Enterprise
        - Evaluating/Trial
    validations:
      required: true

  - type: dropdown
    id: question-category
    attributes:
      label: Question Category
      description: What area does your question relate to?
      options:
        - Initial Setup & Installation
        - Configuration & YAML syntax
        - Merge Rules & Conditions
        - GitHub Integration & Webhooks
        - License & Billing
        - Troubleshooting & Debugging
        - Performance & Optimization
        - Security & Compliance
        - API & Integrations
        - Best Practices & Workflow
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like help with? Be as specific as possible.
      placeholder: "Describe your question or the help you need..."
    validations:
      required: true

  - type: textarea
    id: what-tried
    attributes:
      label: What Have You Tried?
      description: What steps have you already taken to solve this?
      placeholder: |
        - Checked documentation
        - Tried configuration changes
        - Searched existing issues
        - etc.
    validations:
      required: false

  - type: textarea
    id: configuration
    attributes:
      label: Current Configuration
      description: Share your `.automerge-pro.yml` configuration (if relevant, remove sensitive data).
      render: yaml
      placeholder: |
        version: '2.0'
        rules:
          - name: 'my-rule'
            # ... rest of configuration
    validations:
      required: false

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "Describe what you expected to happen..."
    validations:
      required: false

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened instead?
      placeholder: "Describe what actually happened..."
    validations:
      required: false

  - type: input
    id: repository
    attributes:
      label: Repository
      description: Which repository is this question about? (if applicable)
      placeholder: "owner/repository"
    validations:
      required: false

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is this question?
      options:
        - Low - General question, no rush
        - Medium - Affecting current work
        - High - Blocking important functionality
        - Critical - Production issue or urgent deadline
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've checked these resources first
      options:
        - label: I have checked the documentation at docs.automerge-pro.com
          required: false
        - label: I have searched existing GitHub issues
          required: false
        - label: I have tried the sample configurations provided
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this question, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        
        **Need faster support?**
        - **Pro/Enterprise**: Email support@automerge-pro.com for priority response
        - **Community**: Join our Discord at https://discord.gg/automerge-pro
        - **Documentation**: https://docs.automerge-pro.com
        
        **Response Times:**
        - Free tier: Community support via GitHub issues
        - Pro tier: 2-3 business days via email
        - Enterprise tier: 4-8 hours via email + phone support available