version = 0.1

[default.deploy.parameters]
stack_name = "automerge-pro-dev"
s3_bucket = "automerge-pro-sam-deployments"
s3_prefix = "automerge-pro-dev"
region = "us-east-1"
parameter_overrides = "Environment=dev"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"

[staging.deploy.parameters]
stack_name = "automerge-pro-staging"
s3_bucket = "automerge-pro-sam-deployments"
s3_prefix = "automerge-pro-staging"
region = "us-east-1"
parameter_overrides = "Environment=staging"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"

[prod.deploy.parameters]
stack_name = "automerge-pro-prod"
s3_bucket = "automerge-pro-sam-deployments"
s3_prefix = "automerge-pro-prod"
region = "us-east-1"
parameter_overrides = "Environment=prod"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"