// This file should be generated by the Xata CLI.
// To generate it, run the following command in your terminal:
//
// npx xata pull main
//
// You must have a .env file in the root of your project with your XATA_API_KEY for this to work.
//
// After running the command, this file will be populated with a typed Xata client.

export const getXataClient: any : any : any : any = () => {
  throw new Error(
    "Xata client has not been generated. Please run `npx xata pull main` to generate it."
  );
};
