# Example .automerge-pro.yml configuration file
# This file should be placed in the root of your repository

# Enable or disable automerge for this repository
enabled: true

# Merge strategy: 'merge', 'squash', or 'rebase'  
strategy: merge

# Conditions that must be met before auto-merging
conditions:
  # Required status checks that must pass
  required_status_checks:
    - "ci/tests"
    - "ci/lint"
    - "ci/build"
  
  # Number of required approving reviews
  required_reviews: 1
  
  # Whether to dismiss stale reviews when new commits are pushed
  dismiss_stale_reviews: false
  
  # Whether to require reviews from code owners
  require_code_owner_reviews: false
  
  # Labels that must be present for auto-merge
  required_labels:
    - "automerge"
  
  # Labels that block auto-merge
  blocked_labels:
    - "wip"
    - "do-not-merge"
    - "hold"

# Optional: Schedule when auto-merges can happen (Pro/Enterprise feature)
schedule:
  timezone: "America/New_York" 
  hours: [9, 10, 11, 12, 13, 14, 15, 16, 17]  # 9 AM to 5 PM