name: Dependabot Auto-Merge PR

on:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Auto-merge Dependabot PRs
        run: |
          echo "🚀 Force merging ${{ steps.metadata.outputs.update-type }} update (no checks required)"
          echo "Package: ${{ steps.metadata.outputs.dependency-names }}"
          echo "Version: ${{ steps.metadata.outputs.previous-version }} → ${{ steps.metadata.outputs.new-version }}"

          # Approve the PR
          gh pr review --approve "${{ github.event.pull_request.number }}" --body "🚀 Force approved by Dependabot workflow (no checks required) - ${{ steps.metadata.outputs.update-type }} update for ${{ steps.metadata.outputs.dependency-names }}"

          # Enable auto-merge
          gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on major version updates
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-major' }}
        run: |
          gh pr comment "${{ github.event.pull_request.number }}" --body "🔄 **Major version update detected and force merged**

          This PR contains a major version update that may include breaking changes. It was force merged without waiting for checks.

          **Update Details:**
          - **Package:** ${{ steps.metadata.outputs.dependency-names }}
          - **Update type:** ${{ steps.metadata.outputs.update-type }}
          - **Version change:** ${{ steps.metadata.outputs.previous-version }} → ${{ steps.metadata.outputs.new-version }}

          If you encounter any issues after this merge, please review the changelog/release notes for breaking changes."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
