name: Label-based Auto Merge

on:
  pull_request_target:
    types: [labeled, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  label-automerge:
    name: Auto-merge all PRs (no conditions)
    runs-on: ubuntu-latest

    steps:
      - name: Force merge immediately (no checks)
        run: |
          echo "🚀 Force merging PR #${{ github.event.pull_request.number }} immediately (no conditions)"
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "Author: ${{ github.event.pull_request.user.login }}"
          echo "Branch: ${{ github.event.pull_request.head.ref }} -> ${{ github.event.pull_request.base.ref }}"

          # Approve the PR
          gh pr review --approve "${{ github.event.pull_request.number }}" --body "🚀 Force approved and merging immediately (no checks required)"

          # Merge the PR
          gh pr merge --squash "${{ github.event.pull_request.number }}" --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
