name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ github.event_name == 'pull_request' }}

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint || echo "Linting not configured, skipping..."

      - name: Build application
        run: npm run build

      - name: Test build output
        run: |
          ls -la dist/
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            test -f dist/index.html || echo "PR mode: non-blocking build output check"
          else
            test -f dist/index.html
          fi
